//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalBlog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleImages
    {
        public int Id { get; set; }
        public string Path { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> ArticleId { get; set; }
        public string Extension { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
